language: node_js
node_js:
  - "0.11"
before_script:
  - npm install -g grunt-cli
  - npm update
  - mv src/semantic.config.example src/semantic.config
after_script:
  - grunt coveralls
notifications:
  on_success: change
  on_failure: change